services:
  db:
    image: postgres:17
    container_name: bank-db
    restart: always
    environment:
      POSTGRES_DB: "conta"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres123"
    ports:
      - "5432:5432"
    volumes:
      - bank-api-data:/var/lib/postgresql/data
    networks:
      - backend-network
  backend:
    image: luizvinicius/bank-api:1.0
    container_name: bank-backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backend-network
      - frontend-network

volumes:
  bank-api-data:
    name: bank-api-data
networks:
  backend-network:
    name: backend-network
  frontend-network:
    name: frontend-network
