services:
  db:
    image: postgres:17
    container_name: bank-db
    restart: always
    environment:
      POSTGRES_DB: "conta"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres123"
    ports:
      - "5432:5432"
    volumes:
      - bank-api-data:/var/lib/postgresql/data
    networks:
      - backend-network
  backend:
    image: bank-api:1.0
    container_name: bank-backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backend-network
      - frontend-network
  keycloak-db:
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: keycloak123
    ports:
      - "5433:5432"
  keycloak:
      image: quay.io/keycloak/keycloak:26.1.4
      depends_on:
        - keycloak-db
      command:
        - start-dev
      ports:
        - "9082:8080"
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin@123
        KC_DB: postgres
        KC_DB_SCHEMA: public
        KC_DB_USERNAME: postgres
        KC_DB_PASSWORD: keycloak123
        KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
        KC_HOSTNAME: localhost

volumes:
  bank-api-data:
    name: bank-api-data
  pgdata:
    name: "postgres-keycloak-data"
networks:
  backend-network:
    external: true
  frontend-network:
    external: true
