services:
  db:
    image: postgres:17.6
    container_name: bank-db
    restart: always
    environment:
      POSTGRES_DB: "conta"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres123"
    ports:
      - "5432:5432"
  backend:
    image: bank:1.0
    container_name: bank-backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"