services:
  db:
    image: mysql:8.0
    container_name: bank-db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: conta
    ports:
      - "3306:3306"
    volumes:
      - bank-api-data-mysql:/mysql_data:/var/lib/mysql
  backend:
    image: bank-api-mysql:1.0
    container_name: bank-backend-mysql
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  bank-api-data-mysql:
    name: bank-api-data-mysql