apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-back
  name: devops-back
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: devops-back