apiVersion: v1
data:
  dbname: YXBw
  fqdn-jdbc-uri: amRiYzpwb3N0Z3Jlc3FsOi8vbXktcG9zdGdyZXMtZGItcncuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2FwcD9wYXNzd29yZD1ka09NSGZ6ZlhtMHlsclVyektKaFZZaXBlOEY1dWgzNUgzdFdIWFlpamE0TWtHR1QxOTJKTWxobkpXSnJaSlFMJnVzZXI9YXBw
  fqdn-uri: cG9zdGdyZXNxbDovL2FwcDpka09NSGZ6ZlhtMHlsclVyektKaFZZaXBlOEY1dWgzNUgzdFdIWFlpamE0TWtHR1QxOTJKTWxobkpXSnJaSlFMQG15LXBvc3RncmVzLWRiLXJ3LmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9hcHA=
  host: bXktcG9zdGdyZXMtZGItcnc=
  jdbc-uri: amRiYzpwb3N0Z3Jlc3FsOi8vbXktcG9zdGdyZXMtZGItcncuZGVmYXVsdDo1NDMyL2FwcD9wYXNzd29yZD1ka09NSGZ6ZlhtMHlsclVyektKaFZZaXBlOEY1dWgzNUgzdFdIWFlpamE0TWtHR1QxOTJKTWxobkpXSnJaSlFMJnVzZXI9YXBw
  password: ZGtPTUhmemZYbTB5bHJVcnpLSmhWWWlwZThGNXVoMzVIM3RXSFhZaWphNE1rR0dUMTkySk1saG5KV0pyWkpRTA==
  pgpass: bXktcG9zdGdyZXMtZGItcnc6NTQzMjphcHA6YXBwOmRrT01IZnpmWG0weWxyVXJ6S0poVllpcGU4RjV1aDM1SDN0V0hYWWlqYTRNa0dHVDE5MkpNbGhuSldKclpKUUwK
  port: NTQzMg==
  uri: cG9zdGdyZXNxbDovL2FwcDpka09NSGZ6ZlhtMHlsclVyektKaFZZaXBlOEY1dWgzNUgzdFdIWFlpamE0TWtHR1QxOTJKTWxobkpXSnJaSlFMQG15LXBvc3RncmVzLWRiLXJ3LmRlZmF1bHQ6NTQzMi9hcHA=
  user: YXBw
  username: YXBw
kind: Secret
metadata:
  annotations:
    cnpg.io/operatorVersion: 1.27.1
  creationTimestamp: "2025-10-25T22:27:04Z"
  labels:
    cnpg.io/cluster: my-postgres-db
    cnpg.io/reload: "true"
    cnpg.io/userType: app
  name: my-postgres-db-app
  namespace: default
  ownerReferences:
  - apiVersion: postgresql.cnpg.io/v1
    controller: true
    kind: Cluster
    name: my-postgres-db
    uid: 39a1add9-c6bc-45a0-bb38-b84dc7ee979a
  resourceVersion: "132026"
  uid: d09fd258-eda1-4ec3-8c4f-14f0663d127e
type: kubernetes.io/basic-auth